import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Providers";
import { Montserrat } from "next/font/google";
import ClientToaster from "@/components/ClientToaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat_init = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-montserrat',
});



// Inline script: runs before React hydration to set dir & theme class from localStorage
const bootstrapScript = `
(function() {
  try {
    const raw = (typeof window !== 'undefined') ? localStorage.getItem('toolinger_ui') : null;
    if (!raw) return;
    const ui = JSON.parse(raw);
    if (ui?.rtl) document.documentElement.setAttribute('dir', 'rtl');
    else document.documentElement.removeAttribute('dir');

    if (ui?.theme === 'dark') document.documentElement.classList.add('dark');
    else if (ui?.theme === 'light') document.documentElement.classList.remove('dark');

    if (ui?.accent) {
      document.documentElement.style.setProperty('--accent-color', ui.accent);
    }

    if (ui?.boxed) document.documentElement.classList.add('layout-boxed');
    else document.documentElement.classList.remove('layout-boxed');

    if (ui?.sidebarColor) {
      document.documentElement.style.setProperty('--sidebar-bg', ui.sidebarColor);
    }

    if (ui?.layoutMode) {
      document.documentElement.setAttribute('data-layout-mode', ui.layoutMode);
    }
  } catch(e) { console.warn('bootstrapping ui prefs failed', e); }
})();
`.trim();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
        <html lang="en">
          <head>{/* inline script must be in head or top of body so it runs before hydration */}
            <script dangerouslySetInnerHTML={{ __html: bootstrapScript }} />
          </head>
          <body
            className={` ${montserrat_init.className}`}
          >
            {children}
            <ClientToaster />
          </body>
        </html>
      </Providers>
    </>
  );
}
